function Hd = LFP_bandpass_filter
%LFP_BANDPASS_FILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.8 and Signal Processing Toolbox 8.4.
% Generated on: 23-Oct-2021 15:27:22

% modified by June Hoan Kim on 24th November, 2025
% replaced fdesign by designfilt

% Butterworth Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = 30000;  % Sampling Frequency

N   = 4;    % Order
Fc1 = 0.7;  % First Cutoff Frequency
Fc2 = 170;  % Second Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.

% Define the bandpass filter first
Hd = designfilt('bandpassiir', ...
    'FilterOrder', N, ...                % 4th order IIR (fast and stable)
    'HalfPowerFrequency1', Fc1, ...      % lower cut frequency
    'HalfPowerFrequency2', Fc2, ...     % upper cut frequency
    'SampleRate', Fs);

% [EOF]
